- cl_manycore/libraries/Makefile
- cl_manycore/libraries/bsg_manycore_bits.h
- cl_manycore/libraries/bsg_manycore_cuda.h
- cl_manycore/libraries/bsg_manycore_driver.h
- cl_manycore/libraries/bsg_manycore_elf.h
- cl_manycore/libraries/bsg_manycore_errno.h
- cl_manycore/libraries/bsg_manycore_features.h
- cl_manycore/libraries/bsg_manycore_loader.h
- cl_manycore/libraries/bsg_manycore_mem.h
- cl_manycore/libraries/bsg_manycore_memory_manager.h
- cl_manycore/libraries/bsg_manycore_mmio.h
- cl_manycore/libraries/bsg_manycore_tile.h
- cl_manycore/regression/Makefile.common
- cl_manycore/regression/spmd/spmd_tests.h
- cl_manycore/testbenches/cosim/Makefile.common
* This addresses an issue observed when compiling the regressions tests `htole32 undefined`
* This issue occurs when client source files include standard system headers before including `big_manycore_*` headers. 
* This PR addresses the issue by creating a file `bsg_manycore_features.h` which acts as a guard to check that needed C standards are defined. If they are not then the compilation errors out.
* As a result the client will know to add these defines to  their`CFLAGS` variable instead of being confused by linker errors.
* <b> For this fix to work in the future every new library header should include `bsg_manycore_features.h` before any other header</b>
* This PR <b>does not address</b> an outstanding issue in which an invalid file descriptor is passed to `format_packet` and causes …
> adds bsg_manycore_features.h

- scripts/amibuild/ReleaseRepoAction.py
- scripts/amibuild/build.py
* TL; DR - We  can use 'dev' instead of obscure hashes
> Changed how build commits are processed to handle non-commit IDs in AMI build 

- cl_manycore/Makefile.environment
* Sets BASEJUMP_STL_DIR BSG_IP_CORES_DIR BSG_MANYCORE_DIR environment variables
from Makefile.environment.
* Overrides previously set environment variables (warns if this occurs)
> Added Makefile code to check for/include for Bladerunner Makefiles

- cl_manycore/libraries/bsg_manycore_elf.h
- cl_manycore/libraries/bsg_manycore_errno.h
- cl_manycore/libraries/bsg_manycore_loader.cpp
- cl_manycore/libraries/bsg_manycore_loader.h
- cl_manycore/regression/spmd/Makefile.tests
- cl_manycore/regression/spmd/test_symbol_to_eva.c
- cl_manycore/regression/spmd/test_symbol_to_eva.h
* hb_mc_symbol_to_eva() is like symbol_to_eva() but takes a buffer as input instead of a file path.
> New hb_mc_symbol_to_eva function to new API

- cl_manycore/regression/spmd/Makefile
- cl_manycore/testbenches/spmd/Makefile
* Allows users to ignore bsg_cadenv
> Set "Ignore Cadenv" variable before building RISC-V Binaries

- cl_manycore/Makefile
- cl_manycore/Makefile.environment
- cl_manycore/testbenches/Makefile
QoL Improvement. This allows users to run cosimulation tests from in the regression directory without setting the CL_DIR environment variable.
> Moved CL_DIR Definition from root Makefile to Makefile.environment

- cl_manycore/regression/library/test_manycore_credits.c
- hdl/axil_to_mcl.v
- hdl/s_axil_mcl_adapter.v
- The manycore link hardware now checks the receive fifo credits. If the credits are exhausted, host request write will fail.
- Fix the mismatch between the credits counter and the receive fifo elements.
> Credits fix

- cl_manycore/libraries/bsg_manycore_cuda.cpp
- cl_manycore/libraries/bsg_manycore_cuda.h
This pull request addresses issue #92 .
Now users can either call hb_mc_device_program_init that takes in path to binary and automatically loads into a buffer, or call hb_mc_device_program_init_binary with a prepared buffer that contains the binary and binary size. 
hb_mc_device_program_init is separated into three functions: 
1. hb_mc_device_program_init(): load binary from file into buffer and call 2
2. hb_mc_device_program_init_binary(): copy binary buffer and set all variables in device's program_t struct and call 3
3. hb_mc_device_program_load(): loads the binary onto all tiles and unfreezes them.
Cuda regression tests passed, ready to merge.
> Binary loader that accepts buffer instead of path to binary

- cl_manycore/libraries/bsg_manycore_cuda.cpp
- cl_manycore/libraries/bsg_manycore_cuda.h
- cl_manycore/libraries/bsg_manycore_origin_eva_map.cpp
- cl_manycore/libraries/bsg_manycore_origin_eva_map.h
This PR addresses issue #283 . 
Copies content of argument list argv instead of just copying the pointer.
Added hb_mc_tile_group_kernel_init and hb_mc_tile_group_kernel_exit for clean up
Added hb_mc_tile_group_exit for cleanup
Rebased, and all regression tests passed.
> Bug fix in copying argument list in CUDA API

- cl_manycore/libraries/bsg_manycore_cuda.cpp
- cl_manycore/libraries/bsg_manycore_cuda.h
- cl_manycore/regression/cuda/Makefile.tests
This PR addresses issue #175 . 
Introduced 6 new symbols in the cuda_lite_runtime code , cuda_kernel_ptr, cuda_argc, cuda_argv_ptr, cuda_finish_signal_addrl, cuda_finish_signal_val and cuda_kernel_not_loaded_val. The symbols are set by the CUDA API after binary is loaded onto tiles. 
Added the following functions: 
hb_mc_tiles_set_runtime_symbols --> Calls all functions below:
- hb_mc_tile_set_kernel_ptr_symbol
- hb_mc_tile_set_argc_symbol
- hb_mc_tile_set_argv_ptr_symbol
- hb_mc_tile_set_finish_signal_addr_symbol
Changed hb_mc_tiles_set_symbols to hb_mc_tiles_set_config_symbols which also calls two new functions: 
- hb_mc_tile_set_finish_signal_val
- hb_mc_tile_set_kernel_not_loaded_val 
Regression tests passed (F1 and cosim). 
**Should ONLY be merged in together with PR # 65 on the …
> Added functions to Parse runtime variables from elf file in CUDA API 

- cl_manycore/libraries/bsg_manycore_config.cpp
- cl_manycore/libraries/bsg_manycore_config.h
Found this while trying to increase the manycore dimensions
> Bugfix for xdim_max computation in bsg_manycore_config

- cl_manycore/libraries/Makefile
- cl_manycore/libraries/bsg_manycore.cpp
- cl_manycore/libraries/bsg_manycore.h
- cl_manycore/libraries/bsg_manycore_config.h
- cl_manycore/libraries/bsg_manycore_cuda.cpp
- cl_manycore/libraries/bsg_manycore_eva.cpp
- cl_manycore/libraries/bsg_manycore_eva.h
- cl_manycore/libraries/bsg_manycore_loader.cpp
- cl_manycore/libraries/bsg_manycore_vcache.h
- cl_manycore/regression/library/test_manycore_eva.c
- cl_manycore/regression/library/test_manycore_eva_read_write.c
- cl_manycore/regression/spmd/test_bsg_loader_suite.c
* Extends the `hb_mc_manycore` API to support HammerBlade hardware operating without off-chip memory
* Extends the `hb_mc_config` API for values derived from top-level parameters
* Modifies the `hb_mc_eva` API to take an `hb_mc_manycore` instance (it had to be done... I'm sorry)
* Modifies the `default_eva_map` implementation to automatically handle No-DRAM mode
* Modifies the `hb_mc_loader_load` implementation to automatically handle No-DRAM mode
* adds function `hb_mc_manycore_enable_dram()`
* adds function `hb_mc_manycore_disable_dram()`
* modifies `hb_mc_manycore_dram_is_enabled()` to return a runtime value
* adds function `hb_mc_config_get_vcache_block_size()`
* adds function `hb_mc_config_get_vcache_size()`
* `bsg_manycore_eva.cpp` and `bsg_manycore_origin_eva_map.cpp` are compiled …
> Host API for No-DRAM Mode

- cl_manycore/Makefile.environment
* Added support for cadenv
I've added support for cadenv. The default behavior is to use environment variables for VCS and Vivado (since that's necessary for F1/Cornell) but if any UW people want to use cadenv, it will now be found
> Feature cadenv search

- cl_manycore/regression/cuda/Makefile.tests
The bug in matrix multiplication with tile group shared memory that appeared in cosim is now fixed. So the test is added back into the list of regression lists. 
Credit and huge thanks to @drichmond for his help! 
Related PR # 119 in bsg_manycore.
> Add back test_matrix_mul_shared_mem to regression tests

- cl_manycore/testbenches/Makefile
Previously, running `clean` inside of testbenches didn't remove the .so files. Now it does.
> Fixed LIBRARIES_CLEAN variable

- hdl/axil_to_mcl.v
https://github.com/bespoke-silicon-group/bsg_f1/blob/3af08f4f73c8fc4705205c69fe7d1b3d3492381d/hdl/axil_to_mcl.v#L366
Above logic returns credit packets even the fifo is full. So updated it to return credits only when a in-request is accepted, aka yumi is asserted.
> Fixed logic returning credit packets

- cl_manycore/regression/library/test_rom.c
- to expect a cache associativity of <=32 instead of 2.
- to expect a maximum of 4 and 10 for major and minor version number.
Passes F1/Cosim.
> Updated test_rom library regression test

- hardware/hardware.mk
We're still missing some files to make #414  work:
diff master vs PR #414
```
< bsg_arb_fixed.v
38d36
< bsg_cache_wrapper_axi.v
40d37
< bsg_clkgate_optional.v
44d40
< bsg_cycle_counter.v
52d47
< bsg_dlatch.v
54c49
< bsg_fifo_1r1w_large.v
---
> bsg_expand_bitmask.v
56d50
< bsg_fifo_1rw_large.v
71a66,67
> bsg_lru_pseudo_tree_decode.v
> bsg_lru_pseudo_tree_encode.v
73d68
< bsg_manycore_addr.vh
81d75
< bsg_manycore_packet.vh
96,97d89
< bsg_mem_banked_crossbar.v
< bsg_mem_cfg_pkg.v
105d96
< bsg_noc_links.vh
107,109d97
< bsg_nonsynth_mem_1rw_sync_assoc.v
< bsg_nonsynth_mem_1rw_sync_mask_write_byte_assoc.v
< bsg_nonsynth_mem_infinite.v
115d102
< bsg_round_robin_2_to_2.v
120d106
< bsg_thermometer_count.v
129d114
< definitions.vh
144d128
< memory_system.v
147d130
< parameters.vh
159d141
< …
```
> Added missing files to filelist

- libraries/bsg_manycore_cuda.cpp
- regression/cuda/test_binary_load_buffer.c
- regression/cuda/test_binary_load_buffer.h
- regression/cuda/tests.mk
Related to issue #337.
- Added static hb_mc_program_binary_copy() CUDA API function to copy the binary buffer into hb_mc_program_t struct instead of pointing to the buffer.
- Added a cuda regression test test_binary_load_buffer to test the correctness of hb_mc_program_init_binary function that loads binary onto tiles from a pre-loaded buffer instead of loading it from a given path, and to test if the double freeing of binary bug is fixed.
F1 passed.
**merge with PR # 166 in bsg_manycore.**
> Fixes the double freeing of binary bug

- testbenches/simlibs.mk
simlibs.mk requires PROJECT to be set, but it was checked. This is now fixed. 
This PR addresses #421
> Added missing variable check in simlibs.mk

- build/README.md
- build/create_dcp.tcl
- build/synth.tcl
- hardware/axil_to_mcl.v
- hardware/s_axil_mcl_adapter.v
- scripts/amibuild/build.py
There are a few changes here. 
* Documentation (in case we need to upgrade Vivado again in the future)
* IP Version Numbers (See Documentation)
* The Base AMI used by amibuild (to reflect 2019.1 AMI)
> Vivado 2019.1 support / AWS-FPGA v1.4.11

- hardware/cl_manycore.sv
- libraries/bsg_manycore.cpp
- libraries/bsg_manycore.h
- testbenches/sh_dpi_tasks.svh
- testbenches/simlibs.mk
I've rebased the "slow clock" acceleration fix that feeds up IO speeds in cosimulation. @tommydcjung and I had this working back in August and it went stale because we never merged it.
At the moment I rebased it but it doesn't work. For example, the regression test library/test_vcache_simplified doesn't work.
> Accelerate cosimulation IO

- Makefile
- Makefile.machine.include
- hardware/bsg_bladerunner_mem_cfg_pkg.v
- hardware/cl_manycore.sv
- hardware/cl_manycore_pkg.v
- hardware/hardware.mk
- testbenches/Makefile
- testbenches/simlibs.mk
Sorry - this was a specific feedback on my original PR (#438, and corresponding PR #184 in Manycore). 
We don't want to have F1-specific features in bsg_manycore. I didn't communicate this very well, but our goal is to have a bsg_bladerunner_mem_cfg_pkg that defines all the memory types that bladerunner supports in simulation
> Removed dependence on bsg_manycore_mem_cfg_pkg.v

- hardware/cl_manycore.sv
The missing declarations prevent FPGA compilation
> Added missing synopsys translate declarations

- libraries/bsg_manycore_printing.cpp
- libraries/bsg_manycore_printing.h
- testbenches/sh_dpi_tasks.svh
This makes it consistent with BSG Manycore, when reporting time values in simulation
> Re-implemented BSG Time to use $time, instead of $realtime

- regression/cuda/tests.mk
- regression/library/tests.mk
- regression/python/tests.mk
- regression/specint/tests.mk
- regression/spmd/tests.mk
No makefile that includes tests.mk needs the variables defined in
Makefile.machines.include
> Removed Makefile.machines.include from tests.mk

- regression/library/test_vcache_flush.c
- regression/library/test_vcache_sequence.c
- regression/library/test_vcache_stride.c
* test_vcache_flush uses cache parameters in the ROM instead of hardcoded values
* test_vcache_flush enumerates all column caches instead of just column 0
* test_vcache_sequence increments the addresses by word size instead of by byte
> Fix cache regression

- regression/cuda/test_loader.c
- regression/spmd/test_loader.c
* adds a return code to the CUDA test_loader that can be ignored but can be set to non-zero to indicate an application failure.
* fixes a bug in which `ret` is shadowed and results in success being returned even on failure.
> Small fixes and additions to test loader programs

- .gitignore
- hardware/bsg_print_stat_snoop.v
- hardware/cl_manycore.sv
- hardware/hardware.mk
Credit to @tommydcjung 
- Added snooping from the loader_link_sif_li/lo to intercept packets intended for bsg_print_stat and use it as input for vanilla core profiler.
- This fixes the clock domain crossing issue with the print_stat_v_i signal that is on main_clk_a0, vs. the vanilla_core_profiler which is on core_clock.
- Fixes the missing print_stat signals issue # 205 in bsg_manycore.
Cosim Regression passed.
> Adds snooping the bus to axi_to_mcl for print_stat packets 

- libraries/bsg_manycore.cpp
- libraries/bsg_manycore_epa.h
- libraries/bsg_manycore_errno.h
- regression/library/test_manycore_alignment.c
- regression/library/test_manycore_alignment.h
- regression/library/test_manycore_vcache_sequence.c
- regression/library/tests.mk
Related to issue #477 .
credit to @save-buffer and @drichmond.
- Added hb_mc_epa_check_alignment function to check for correct address alignment based on size.
- Moved all alignment functions in hb_mc_manycore_write8/16/32, hb_mc_manycore_write_mem, and hb_mc_manycore_memset function down one level to hb_mc_manycore_write function
- Modified test_manycore_vcache_sequence test write into correctly aligned addresses, and added writes to misaligned addresses to make sure the HOST API catches them.
COSIM regression passed, ready to merge.
> Fixes the alignment check issue for Host API

- libraries/bsg_manycore.cpp
* fixes #483
* decouples reading response packets from the masking of response data
> Fix for 483

- hardware/axil_to_mcl.v
- hardware/bsg_bladerunner_rom.v
- hardware/bsg_manycore_wrapper.v
- hardware/bsg_print_stat_snoop.v
- hardware/cl_manycore.sv
- hardware/cl_manycore_pkg.v
- machines/4x4_amo_support
- machines/4x4_blocking_vcache_f1_model/Makefile.machine.include
* modifies mcl for refactor network packet
* removes load_id_width_p where no longer applicable
* removes load_id_width_p from vcache instantiation
* removes load_id_width_p from cl_manycore_pkg
* removes load_id_width_p from non-blocking vcache instantiation
* removes load_id_width_p from bsg_bladerunner_rom
* removes deprecated cordinate ports from blocking vcache
* adds machine configurations for AMO support
> AMO support

- Makefile.machine.include
- libraries/libraries.mk
- machines/4x16_non_blocking_vcache_ramulator_hbm/Makefile.machine.include
- machines/4x32_non_blocking_vcache_ramulator_hbm/Makefile.machine.include
- machines/4x4_blocking_vcache_f1_model/Makefile.machine.include
- machines/4x8_non_blocking_dramsim3_hbm2_4gb/Makefile.machine.include
- machines/4x8_non_blocking_vcache_ramulator_hbm/Makefile.machine.include
- regression/compilation.mk
- regression/regression.mk
- testbenches/cosimulation.mk
- testbenches/link.mk
- testbenches/simlibs.mk
* Removed a few unnecessary checks
* Moved rule declarations to more relevant files
* Added BSG_MACHINE_NAME to all Makefile.machine.include
@vb000 @tommydcjung - Can you give input on the new BSG_MACHINE_NAME variable? I'm using this to build machine-specific crt.o files so that someone can't run with the wrong crt.o file for a machine, among other things.
@mrutt92 for LGTM
> Make Flow modifications

- libraries/bsg_manycore_cuda.cpp
- libraries/bsg_manycore_cuda.h
This is a PR from a long time ago. I increased code reuse.
It does rely on passing 0,0 to the initializer. If this controversial, let me know. I did comment it though
> Reuse CUDA init_custom_dimension in global init

- hardware/bsg_manycore_wrapper.v
This may be superseded by Max's work
> Removed deprecated parameters in bsg_manycore_wrapper

- testbenches/dramsim3.mk
Now libdramsim3.so is removed all the time
> Changed location of dramsim3 clean rule

- build/Makefile
Set BSG_MACHINE_PATH in the `build` directory so that it's impossible (or at least very hard) to build a machine that can't be synthesized.
> Set build machine to prevent compiling unsynthesizable hardware

- .gitignore
- Makefile
- machines/.gitignore
- regression/cuda/rules.mk
- regression/specint/rules.mk
- regression/spmd/rules.mk
- testbenches/.gitignore
This PR simply solves #532, by forcing a rebuild whenever the relevant program is run (through the makefile)
It is a less heavy-handed change than before.
I also moved some .gitigore directives that were semi-relevant
> Fixed #532 - Rebuild CUDA Binaries at runtime.

- hardware/cl_manycore.sv
As title says, fixed the manycore clock frequency using the USING_DRAMSIM3 macro
No idea if this is the right way to do it, yet. Will test it out
> Added support for running Manycore at HBM frequency

- hardware/cl_manycore.sv
The infinite memory module in bsg_manycore has been updated to address issue where much more memory was allocated per simulation than was needed.
This updates bsg_replicant to accommodate the change.
> updated to use new infmem module

- Makefile
- testbenches/Makefile
This is probably long overdue, but running regression from testbenches now produces a runtime.log file that records the execution time (as reported by VCS) of each testbench.
That runtime.log file is copied into BSG_MACHINE_PATH, so that running regression on multiple machines produces runtime.log files for each machine. 
Anything else that people want in this? @proftaylor 
For example, I might be able to report manycore core clock cycles.
> Regression now produces runtime measurements

- libraries/bsg_manycore_cuda.cpp
* The memory allocator now aligns based on the victim cache's block size.
> malloc uses the cache size as the alignment instead of hardcoded 32

- libraries/bsg_manycore_cuda.cpp
- libraries/bsg_manycore_cuda.h
Adds type safe alternatives to `hb_mc_device_memcpy`.
> adds a type safe cuda memcpy

- hardware/bsg_manycore_endpoint_to_fifos.v
- hardware/bsg_manycore_endpoint_to_fifos_pkg.v
- hardware/bsg_manycore_link_to_axil.v
- hardware/cl_manycore.sv
- hardware/hardware.mk
Moving to Verilator, this module was slightly problematic. Several parameters had unnecessary global scope, and were included in a parameter file that was outside of the context of the endpoint-to-fifo module.
In addition, it seems like we had duplicate stat-print snoop logic. I removed that, as well.
* Removed some global parameters, that could be computed from local parameters (!!!)
* Removed Endpoint-To-FIFO dependence on AXI-L parameters
* Removed duplicate statistics snooping logic
> Minor refactoring of the Endpoint-To-FIFO module

- hardware/cl_manycore.sv
Due to varying frequencies of cosimulation during IO vs. compute, print_stat_v signal is not being detected by the vcache_profiler module and vcache stats are not being printed.  Switched the incoming stats profiler's signal to come from the snooping module, similar to the vanilla_core_profiler.
> Snooping vcache profiler's incoming print_stat_v signal

- libraries/bsg_manycore_cuda.cpp
- libraries/bsg_manycore_cuda.h
- regression/cuda/test_memory_leak.cpp
- regression/cuda/test_memory_leak.hpp
- regression/cuda/tests.mk
1. API now resets the number of tile groups to zero in the host, after every hb_mc_tile_groups_execute call.
2. API allocates a space in device DRAM to store kernel arguments before tile group launch, it now frees that location after tile group is executed.
3. Adds a memory_leak regression test to make sure CUDA Lite API does not have memory leak on launching tile groups.
**merge with PR # 317 in bsg_manycore.**
> CUDA Malloc Bugfix in API

- libraries/bsg_manycore.cpp
- libraries/bsg_manycore.h
- libraries/bsg_manycore_config.h
- libraries/bsg_manycore_platform.cpp
- libraries/bsg_manycore_platform.h
- libraries/libraries.mk
- regression/library/test_rom.c
I've introduced the idea of platforms. Platforms are the host medium for running a manycore, be it FPGA, VCS, or Verilator. This PR splits `bsg_manycore.cpp` into two files: 
`bsg_manycore.cpp`: Manycore API - data copy in/out, packet tx/rx
`bsg_manycore_platform.cpp`: platform-specific tx/rx, initialization
This should make supporting new machines easier. This work would have been needed eventually to support Black Parrot. It has probably already been done by Paul. It was definitely already done by me, for Verilator.
I also took the liberty of removing some old, outdated code. This simplifies the interface between manycore software and platform.
> Split out machine-specific functionality into new file

- hardware/hardware.mk
- libraries/bsg_manycore.cpp
- libraries/bsg_manycore.h
- libraries/bsg_manycore_config.h
- libraries/bsg_manycore_platform.h
- libraries/features/README.md
- libraries/features/dma/bsg_manycore_dma.h
- libraries/features/dma/noimpl/bsg_manycore_dma.cpp
- libraries/features/dma/noimpl/feature.mk
- libraries/features/dma/simulation/bsg_manycore_dma.cpp
- libraries/features/dma/simulation/dramsim3.mk
- libraries/features/dma/simulation/feature.mk
- libraries/features/dma/simulation/infmem.mk
- libraries/features/dma/simulation/libdmamem.mk
- libraries/libraries.mk
- libraries/platforms/aws-fpga/library.mk
- libraries/platforms/aws-vcs/hardware.mk
- libraries/platforms/aws-vcs/library.mk
Platforms can support different features. For example, we support DMA in simulation, but not on the FPGA (though we could). This change will also encapsulate MMIO, where in simulation we use the DPI interface, and on the FPGA we use PCIe (another PR). I'm sure there are other features we'll add in the future. 
In this PR I split the cosim-specific DMA into a new file and defined an API. F1 uses the "noimpl" driver, but all the functions do is return HB_MC_NOIMPL.
This PR also moves the makefiles fragments `infmem.mk` `libdmamem.mk` and `libdramsim3.mk` into the `features/dma/simulation` directory. 
This removes the last COSIM macro checks in bsg_manycore.cpp. There are a couple more in bsg_manycore_printing (probably my next PR).
This is currently based on top of #590. It passes …
> Split DMA into feature-specific files

- libraries/bsg_manycore_cuda.cpp
to make sure tiles are frozen before terminating.
Cosimulation in progress.
> Added host_request_fence to the end of hb_mc_device_finish 

- libraries/platforms/aws-fpga/hardware/cl_manycore.sv
Cosim regression passes with 4x4_fast_n_fake, 4x4_blocking_vcache_f1_model and timing_v0_8_4.
Related to Issue #589 .
> Minor bug fix in vanilla core profiler parameter

- examples/cuda/Makefile
These tests currently fail, after the introduction of the HardFloat FPU. I am removing them for now and will file an issue for tracking
> Removed Conv1D and Conv2D tests

- examples/library/test_manycore_init.c
- libraries/platforms/aws-fpga/bsg_manycore_platform.cpp
* Updated regression test
Fails regression before (without updated library), passes after
> Added a check in platform library to prevent reused IDs

- libraries/platforms/aws-vcs/execution.mk
Title is self-explanatory. Passes with machines 4x4_fast_n_fake, 4x4_blocking_vcache_f1_model, timing_v0_8_4
> bugfix in execution Makefile to avoid removing intermediate stats after cosim

- examples/Makefile
- examples/library/Makefile
- examples/library/test_get_cycle.cpp
- examples/library/test_get_cycle.hpp
- libraries/bsg_manycore.cpp
- libraries/bsg_manycore.h
- libraries/bsg_manycore_platform.h
- libraries/platforms/aws-fpga/bsg_manycore_mmio.h
- libraries/platforms/aws-fpga/bsg_manycore_platform.cpp
- libraries/platforms/aws-fpga/hardware/bsg_manycore_link_to_axil.v
- libraries/platforms/aws-fpga/hardware/bsg_manycore_link_to_axil_pkg.v
- libraries/platforms/aws-fpga/hardware/cl_manycore.sv
The cycle counter is a platform level feature, since each platform will implement it differently. This implementation is for AWS (both simulation and emulation). The cycle counter can be read by the host at any time, and is located in the AXI to MCL Interface.
Verilator also supports this, but it is in a different branch.
At the platform level, each platform is required to implement hb_mc_platform_get_cycle. This is exposed at the manycore level through hb_mc_manycore_get_cycle (with the same API). 
I have not exposed this at the CUDA level. It would be possible to call get_cycle after a kernel terminates, but this will cause a small (20 cycle?) latency between when the packet is seen in the fifo, and when get_cycle is read (~20 cycles to read a packet out, in simulation). 
I've added an …
> Added cycle counter interface in HDL and in Software

- libraries/platforms/aws-vcs/link.mk
Make doesn't match %.debug when it is the second target in a rule, so I separated the targets.
> Fix %.debug build for aws-fpga

- examples/cuda/Makefile
- examples/cuda/test_tracer.cpp
- examples/cuda/test_tracer.hpp
- libraries/bsg_manycore.cpp
- libraries/bsg_manycore.h
- libraries/bsg_manycore_platform.h
- libraries/features/profiler/noimpl/bsg_manycore_profiler.cpp
- libraries/features/profiler/simulation/bsg_manycore_profiler.cpp
- libraries/features/tracer/bsg_manycore_tracer.hpp
- libraries/features/tracer/noimpl/bsg_manycore_tracer.cpp
- libraries/features/tracer/simulation/bsg_manycore_tracer.cpp
- libraries/platforms/aws-fpga/bsg_manycore_platform.cpp
- libraries/platforms/aws-fpga/hardware/cl_manycore.sv
- libraries/platforms/aws-vcs/hardware.mk
- libraries/platforms/aws-vcs/library.mk
Depends on [346](https://github.com/bespoke-silicon-group/bsg_manycore/pull/346/files)
This adds an API for enabling/disabling trace file and log file generation. This can drastically reduce runtime and trace file size when datasets are large. 
This is necessary because parsing "plus args", i.e. `+trace` isn't clean in Verilator.
The four new functions are
`bsg_manycore_trace_enable/disable` and `bsg_manycore_log_enable/disable`. The former creates `vanilla_operation_trace.csv` and the latter generates `vanilla.log`
Also added a regression test/example.
> Add tracer C/C++ API

- libraries/features/dma/simulation/dramsim3.mk
- libraries/libraries.mk
Fixes library compilation, when `make regression` is called in the python examples directory. Compilation flags cause the libraries compilation to fail.
Fixes #611
> Fixed leaking CFLAGS/LDFLAGS

- libraries/platforms/aws-vcs/msg_config.mk
Hardfloat generates a bunch of lint messages. Are these relevant? I'm not sure, so I've edited msg_config to ignore them
> Added hardfloat lint messages to msg_config

- examples/cuda/Makefile
- examples/cuda/test_conv1d.c
- examples/cuda/test_conv2d.c
The root cause was how x86 compilers handle FMA.
In the new HardFloat FPU pipeline, we provide an fma instruction. The new compiler flags enable this instruction in the RISC-V code. fma has different precision than doing fmul + fadd, so this produces errors in direct floating-point comparison between the two instruction sequences.
On x86, FMA is not used and the compiler uses fmul (x86) and fadd (x86), not the SSE/AVX fma instruction. On the pre-hardFloat pipeline this was fine, because RISC-V did the same. However, with the new pipeline x86 fmul + fadd produces a different result than RISC-V fma. 
I've switched the host code to use fmaf -- which is the floating point FMA equivalent from the standard library. This produces the IEEE-compliant result and doesn't require gcc flags.
See more …
> Fixed floating-point errors in convolution examples

- libraries/platforms/aws-fpga/hardware/cl_manycore.sv
- libraries/platforms/dpi-verilator/hardware/dpi_top.sv
PR [#331](https://github.com/bespoke-silicon-group/basejump_stl/pull/331/) in BaseJump introduced new parameters to bsg_nonsynth_dramsim3
Credit to @farzamgl for being helpful, and responsive to changing the PR to make it easier to adjust this in HB.
> Update DRAMSim3 Structs for Farzam's PR in BaseJump

- hardware/hardware.mk
- libraries/features/profiler/simulation/bsg_manycore_profiler.cpp
- libraries/platforms/aws-fpga/hardware/bsg_manycore_wrapper_mesh.v
- libraries/platforms/aws-fpga/hardware/cl_manycore.sv
- libraries/platforms/dpi-verilator/hardware/dpi_top.sv
- machines/16x8_fast_n_fake/Makefile.machine.include
- machines/4x4_blocking_dramsim3_hbm2_512mb/Makefile.machine.include
- machines/4x4_blocking_vcache_f1_dram/Makefile.machine.include
- machines/4x4_blocking_vcache_f1_model/Makefile.machine.include
- machines/4x4_fast_n_fake/Makefile.machine.include
- machines/8x4_blocking_dramsim3_hbm2_4gb/Makefile.machine.include
- machines/baseline_v0_16_8/Makefile.machine.include
- machines/baseline_v0_32_16/Makefile.machine.include
- machines/baseline_v0_64_32/Makefile.machine.include
- machines/baseline_v0_8_4/Makefile.machine.include
- machines/timing_v0_16_8/Makefile.machine.include
- machines/timing_v0_32_16/Makefile.machine.include
- machines/timing_v0_64_32/Makefile.machine.include
- machines/timing_v0_8_4/Makefile.machine.include
* hetero_type_vec_gp is now defined in bsg_bladerunner_pkg.v
* Vanilla Core profiler module checks before instantiation
* Only supports mesh network
Pulled from @ptpan's changes
> (Re-?) Added support for heterogeneous machines

- libraries/platforms/aws-fpga/hardware/bsg_manycore_wrapper_mesh.v
- libraries/platforms/aws-fpga/hardware/bsg_mcl_axil_fifos_master.v
- libraries/platforms/aws-fpga/hardware/bsg_mcl_axil_fifos_slave.v
- libraries/platforms/aws-fpga/hardware/cl_manycore.sv
* ready_o -> ready_and_o
* Fixed parameter array length mis-declaration
* Fixed swapped translate off/on
> Verilog fixes for aws-fpga/aws-vcs platform

- hardware/hardware.mk
- libraries/platforms/aws-fpga/hardware/bsg_manycore_wrapper_mesh.v
- libraries/platforms/dpi-verilator/hardware/dpi_top.sv
- machine.mk
- machines/16x8_fast_n_fake/Makefile.machine.include
- machines/4x4_blocking_vcache_f1_dram/Makefile.machine.include
- machines/4x4_blocking_vcache_f1_model/Makefile.machine.include
- machines/4x4_fast_n_fake/Makefile.machine.include
- machines/8x4_blocking_dramsim3_hbm2_4gb/Makefile.machine.include
- machines/baseline_v0_16_8/Makefile.machine.include
- machines/baseline_v0_32_16/Makefile.machine.include
- machines/baseline_v0_64_32/Makefile.machine.include
- machines/baseline_v0_8_4/Makefile.machine.include
- machines/timing_v0_16_8/Makefile.machine.include
- machines/timing_v0_32_16/Makefile.machine.include
- machines/timing_v0_64_32/Makefile.machine.include
- machines/timing_v0_8_4/Makefile.machine.include
- machines/timing_v1_16_8/Makefile.machine.include
- machines/timing_v1_32_16/Makefile.machine.include
- machines/timing_v1_8_4/Makefile.machine.include
* Renamed bsg_manycore to bsg_manycore_top_mesh
* Added network config package feature
* Added ruche network machines
Think of this as half a PR. This adds ruche networks (and they work!) but it's not as clean as I'd like. Makefile.machine.include files have a lot of parameters, and we need to add infinite memory ruche networks.
Since we're adding new machine parameters in [#447](https://github.com/bespoke-silicon-group/bsg_manycore/pull/447), and in this PR, and looking ahead to BP integration, and other top levels - I pushed a clean up of the machine files into my next PR.
> Add support for ruche networks

- libraries/platforms/dpi-verilator/hardware/dpi_top.sv
This PR with [#378](https://github.com/bespoke-silicon-group/basejump_stl/pull/378) fixes this repository for new versions of VCS. 
Casting between logic and bit types now produces extra positive/negative transitions at T=0 in simulation. This can cause unwanted and inaccurate assertions.
The PR in basejump provides bit inputs and outputs for the reset generator. This PR switches the "wire" type to bit, to avoid spurious edges between the clock generator and the reset generator. Backward compatible behavior is maintained for other modules by casting the bit clock into a logic clock in the testbench.
Users can now choose between the bit and logic versions of the clock and reset wires.
Also added a comment describing the behavior.
> Use logic & bit wires for nonsynth reset & clk generator

- libraries/bsg_manycore_config.h
It's annoying to have unused variables in header files.
> Removed unused variable to fix compilation warning

- libraries/bsg_manycore.cpp
- libraries/bsg_manycore_epa.cpp
- libraries/bsg_manycore_epa.h
- libraries/libraries.mk
Super useful when writing a DPI tile. Also, just generally useful when checking addresses.
> Move epa_check_alignment from bsg_manycore.cpp into bsg_manycore_epa.h

- examples/library/Makefile
- examples/library/test_coordinate.cpp
- examples/library/test_coordinate.hpp
- libraries/bsg_manycore_coordinate.h
- libraries/bsg_manycore_errno.h
The core CUDA-Lite code has quite a bit of loop logic that makes the over all code hard to follow.
This PR provides a helper loop macro to simplify code.
> Adds conveniance iterators for looping over coordinate space

- examples/library/test_manycore_alignment/main.c
- examples/library/test_manycore_credits/main.c
- examples/library/test_manycore_dmem_read_write/main.cpp
- examples/library/test_manycore_dram_read_write/main.c
- examples/library/test_manycore_eva/main.c
- examples/library/test_manycore_packets/main.c
- examples/library/test_manycore_vcache_sequence/main.c
- examples/library/test_printing/main.c
- examples/library/test_struct_size/main.c
- examples/library/test_vcache_sequence/main.c
- examples/library/test_vcache_simplified/main.c
- libraries/bsg_manycore_eva.cpp
- libraries/bsg_manycore_loader.cpp
- libraries/bsg_manycore_memory_manager.cpp
- libraries/bsg_manycore_memory_manager.h
This PR removes cruft headers from the library tests and adds a macro guard around the use of mutexes. 
- Removes the use of sys/ioctl.h
- Removes the use of sys/mman.h
- Adds a ifdef around the memory manager mutex (using _MMAN_MUTEX_)
> Removing cruft headers from library tests and guarding mutexes in the memory manager

- README.md
- machines/README.md
- machines/bigblade_pod_X1Y1_ruche_X16Y8_hbm/Makefile.machine.include
- machines/pod_X1Y1_ruche_X16Y8_hbm/Makefile.machine.include
- machines/pod_X1Y1_ruche_X16Y8_hbm_one_pseudo_channel/Makefile.machine.include
- machines/pod_X2Y2_ruche_X16Y8_hbm/Makefile.machine.include
- machines/pod_X4Y4_ruche_X16Y8_hbm/Makefile.machine.include
Update READMEs to remove AWS instructions, describe available simulation machines.
At the moment AWS simulation and compilation is not supported. The recommended development path is VCS + DPI simulation for now. 
Thinking through the problem, AWS simulation will require a couple of new features in the top level: 
1. AXI-Wormhole connections for memory. This is how the caches communicate with DDR.
2. Updating the RTL and platform C++ for the changes to the credit interface (See #698)
I would recommend starting with a new top level that mimics (or uses?) the code in https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/testbenches/common/v/bsg_nonsynth_manycore_testbench.v but without the non-synthesizable bits (DRAMSim3, infinite test memories, etc)
> Update documents and machine configurations

- libraries/platforms/bigblade-verilator/bsg_manycore_platform.cpp
- libraries/platforms/bigblade-verilator/bsg_manycore_simulator.cpp
There were two issues:
1. top->finish() wasn't being called to trigger final blocks in Verilator
2. the deconstructor for SimulationWrapper wasn't being called, so the call site for adding top->finish() wasn't reached
> Call top->finish() during program exit

- machines/pod_X1Y1_ruche_X16Y8_hbm_one_pseudo_channel/Makefile.machine.include
WARNING: EXTREMELY CONTROVERSIAL CHANGE.
bsg_nonsynth_dpi_clock_gen requires even clock period to function properly. Let's be nice to verilator
> DIV2 clock period

- examples/cuda/riscv.mk
Old versions of bash do not like |&. 2>&1 has the same functionality but greater compatibility: https://stackoverflow.com/questions/20553916/syntax-error-near-unexpected-token-using
> Change pipe structure for bash compatibility

- examples/cuda/test_mulh_inference/Makefile
- examples/cuda/test_mulh_inference/kernel.cpp
- examples/cuda/test_mulh_inference/main.c
This test causes GCC to infer MULH instructions, resulting in: TOP.replicant_tb_top.testbench.DUT.py[0].podrow.px[0].pod.mc_y[0].mc_x[0].mc.y[0].x[0].tile.proc.h.z.vcore: Unsupported instruction: 03f5b4b3"
With updated GCC from: https://github.com/bespoke-silicon-group/riscv-gcc/pull/3
> Adding mulh inference test

- examples/.gitignore
- examples/cuda/riscv.mk
Changing disassembly target to dump to a file, which seems to be more useful. Also adding a target for dumping raw object files, which is useful for if you're terrible with debugging compilation flows like me
> Adding object disassembly code

- .gitignore
- examples/library/test_manycore_atomic_packets/Makefile
- examples/library/test_manycore_atomic_packets/main.c
- libraries/bsg_manycore.cpp
- libraries/bsg_manycore.h
This PR adds the ability to do AMO.ADDs from host to manycore DRAM space. This can be useful for synchronization between host and device
Question: Is there a low-overhead function to detect that an NPA is a DRAM address? Would like to add the check to amoadd because I believe sending an AMOADD to a vcore tile could cause a hang.
> Adding atomic packet example

- libraries/bsg_manycore_request_packet_id.h
Currently when compiling the libraries with GCC version >=11, it shows the following error:
```
bsg_bladerunner/bsg_replicant/libraries/bsg_manycore_request_packet_id.h:125:40: error: no matching function for call to ?request_packet_id::request_packet_id(<brace-enclosed initializer list>, <brace-enclosed initializer list>, <brace-enclosed initializer list>, int)?
125 |         request_packet_id(addr, x, y, 1)
```
I tested the fix (c++11 uniform initialization) on CentOS 7, Rocky 8 and 9, with GCC 4, 7, 8, 9 ,10, 11, 12 and 13, fine with c++11, 14, 17 and 20
This fix would be helpful when porting our flow onto Rocky 9 in the future
> Fix c++ initializer in GCC version >=11

- cadenv.mk
- platform.mk
Fixes #846
Tested working in the following conditions:
- `BSG_PLATFORM = bigblade-vcs`, `bsg_cadenv` exists (`DVE` defined), regression working, no error message
- `BSG_PLATFORM = bigblade-vcs`, `bsg_cadenv` does not exist, vcs env correctly set in platform.mk, regression working, no error message
- `BSG_PLATFORM = bigblade-vcs`, `bsg_cadenv` does not exist, host OS vcs env not set, printing error messages, regression does not run
- `BSG_PLATFORM = bigblade-vcs`, `bsg_cadenv` does not exist, host OS vcs env correctly set, regression working, no error message
- `BSG_PLATFORM = bigblade-fpga`, `bsg_cadenv` does not exist, host OS vcs env not set, no error message, regression working
> Move VCS environment checking from cadenv.mk to platform.mk

- hardware/hardware.mk
- libraries/platforms/common/dpi/hardware/dpi_top.sv
Related to [bsg_manycore PR 715](https://github.com/bespoke-silicon-group/bsg_manycore/pull/715)
This PR fixes the `bigblade-verilator` platform simulation error bug. Parameter `num_vcache_rows_p` was deprecated in the `bsg_nonsynth_manycore_testbench` module, need to update `dpi_top` accordingly.
> Deprecate num_vcache_rows_p in RTL

- examples/spmd/Makefile
- examples/spmd/bsg_attr_noalias_ex/Makefile
- examples/spmd/bsg_attr_noalias_remote_ex/Makefile
- examples/spmd/bsg_attr_remote_ex/Makefile
- examples/spmd/bsg_barrier_amoadd_test/Makefile
- examples/spmd/bsg_mcs_mutex_test/Makefile
- examples/spmd/bsg_set_tiles_x_y_asm/Makefile
- examples/spmd/bsg_simple_mutex_test/Makefile
- examples/spmd/credit_pkt_regfile_corrupt_test/Makefile
- examples/spmd/energy_lr_aq_test/Makefile
- examples/spmd/float_logf/Makefile
- examples/spmd/hw_barrier_16x8_interrupt_test/Makefile
- examples/spmd/hw_barrier_NxN_test/Makefile
- examples/spmd/hw_barrier_context_switch_test/Makefile
- examples/spmd/hw_barrier_csr_test/Makefile
- examples/spmd/hw_barrier_reconfigure_test/Makefile
- examples/spmd/icache_miss_bombing/Makefile
- examples/spmd/icache_miss_double_loop_test/Makefile
- examples/spmd/interrupt_handler_asm_example/Makefile
- examples/spmd/memtest2022/Makefile
- examples/spmd/pc_profiler/Makefile
- examples/spmd/stall_remote_ld_wb/Makefile
- examples/spmd/strider/Makefile
Fixes #844 
Currently the SPMD regression does not run at all. After fixing the regression runs.
- Add missing SPMD tests on the latest bsg_manycore repo. For each new test, the pod dimensions are identical to the specific bsg_manycore Makefiles.
- Filter out missing tests automatically as a future-proof fix
> SPMD Makefile Hot Fix

- cadenv.mk
- libraries/platforms/bigblade-vcs/execution.mk
- libraries/platforms/bigblade-vcs/link.mk
- platform.mk
Fixes #856 
- Fall back to vcs if vcs-mx does not exist on the machine
- Define `VCS_BIN` and `VERDI_BIN` so that we no longer rely on the system PATH, and we can choose between vcs and vcs-mx explicitly
> VCS Platform CADENV Optimizations

- examples/library/test_dma/main.cpp
- libraries/bsg_manycore.cpp
- libraries/bsg_manycore_cuda.cpp
- libraries/features/dma/bsg_manycore_dma.h
- libraries/features/dma/simulation/bsg_manycore_dma.cpp
- machines/pod_X1Y2_ruche_X4Y2_hbm/Makefile.machine.include
- machines/pod_X2Y1_ruche_X4Y2_hbm/Makefile.machine.include
- machines/pod_X2Y2_ruche_X4Y2_hbm/Makefile.machine.include
* Adds a 2x2, 2x1, and 1x2 pods machine for simulation with each pod shaped as 4x2.
* Fixes a buggy print in CUDA on init when it tries to report failure.
* Adds clarifying error prints in manycore.cpp.
> Small multipod machine file

- libraries/platforms/bigblade-fpga/hardware.mk
- libraries/platforms/common/dpi/hardware.mk
- libraries/platforms/deprecated/aws-fpga/hardware.mk
Support OS that does not have python2 installed (like Rocky 9)
On CentOS 7: unversioned `python` call is pointing to `python2`, so behavior is unchanged
On Rocky 8 and 9: unversioned `python` call is equivalent to `python3`. With the [latest basejump_stl PR](https://github.com/bespoke-silicon-group/basejump_stl/pull/732), python3 can generate the same rom as before.
Side effect: Users on Rocky 8 and 9 must upgrade to the latest basejump_stl
> Replace python2 with unversioned python
