cl_manycore/libraries/Makefile, cl_manycore/libraries/bsg_manycore_printing.cpp, cl_manycore/libraries/bsg_manycore_printing.h, cl_manycore/regression/library/Makefile.tests, cl_manycore/regression/library/library_tests.h, cl_manycore/regression/library/test_printing.c, cl_manycore/regression/library/test_printing.h, cl_manycore/testbenches/cosim/Makefile.common
* Adds print macros that should be used by the library (or any one else) instead of `fprintf()`
* By using these macros, it is easier to silence/modify the behavior of certain message like debug, error, or warnings statically. At the moment, only compile-time disabling of debug messages is implemented.
Here is the results of regression in `library`:
```
PASS! All 10 tests passed for library
```
and in `spmd`
```
PASS! All 1 tests passed for spmd
```
Here are the logs from running `cat */*.log` in `cl_manycore/regression`.
```
BSG INFO: test_dmem_read_write Regression Test (F1)
BSG INFO: Writing to DMEM
BSG INFO: Write successful
BSG INFO: Completed read
BSG INFO: Read packet data: 0xabcd
BSG REGRESSION TEST PASSED
BSG INFO: test_dram_packets Regression Test (F1)
BSG INFO: Min Address: …
```
=> initial implementation of bsg_pr_* functions

cl_manycore/libraries/bsg_manycore_bits.h, cl_manycore/libraries/bsg_manycore_cuda.h, cl_manycore/libraries/bsg_manycore_driver.cpp, cl_manycore/libraries/bsg_manycore_driver.h, cl_manycore/libraries/bsg_manycore_elf.cpp, cl_manycore/libraries/bsg_manycore_loader.h, cl_manycore/libraries/bsg_manycore_mem.cpp, cl_manycore/libraries/bsg_manycore_mem.h, cl_manycore/libraries/bsg_manycore_memory_manager.cpp, cl_manycore/libraries/bsg_manycore_tile.h
Switched to conditionally include the c++ versions of c headers. Passes both cosim and on f1. 
Addresses #202
=> switched to cpp headers

cl_manycore/regression/library/test_rom.c
=> Fixed test_rom logic check

cl_manycore/regression/library/Makefile.tests, cl_manycore/regression/library/test_rom.c
=> Swapped test_rom order and added a "Have you Programmed your FPGA"? message

cl_manycore/libraries/Makefile, cl_manycore/libraries/bsg_manycore.h, cl_manycore/libraries/bsg_manycore_config.h, cl_manycore/libraries/bsg_manycore_coordinate.h, cl_manycore/libraries/bsg_manycore_eva.cpp, cl_manycore/libraries/bsg_manycore_npa.h, cl_manycore/libraries/bsg_manycore_tile.h, cl_manycore/regression/library/test_vcache_flush.c, cl_manycore/regression/spmd/test_bsg_loader_suite.c
* The branch name is a misnomer. Trust the PR name -- not the branch name.
* Implements the default_npa_to_eva function.
* This should not be merged in until a regression suite has been added to test this feature.
=> Master NPA to EVA

cl_manycore/hardware/Makefile.include, cl_manycore/hardware/cl_manycore.sv
Move host io to origin coordinate and remove the bladerunner rom in NPA address.
This comes with bsg_manycore PR #30
=> move host to (0,0)

cl_manycore/libraries/bsg_manycore_config.h, cl_manycore/libraries/bsg_manycore_eva.cpp, cl_manycore/libraries/bsg_manycore_tile.cpp, cl_manycore/libraries/bsg_manycore_tile.h
* Moved DMEM SIZE from Tile to Config
* Added config parameter to local EVA translation methods
* Unified DRAM Size Calculation
=> Refactored a few constants into config

cl_manycore/regression/Makefile.common
=> Regression stdout redirection

cl_manycore/regression/spmd/Makefile
=> Rebuild RISC-V Manycore binary on every regression run

cl_manycore/libraries/bsg_manycore_loader.cpp, cl_manycore/regression/spmd/test_symbol_to_eva.c
* This should be merged with https://github.com/bespoke-silicon-group/bsg_manycore/pull/55
=> Master loader paddr

cl_manycore/libraries/bsg_manycore_cuda.h
Band aid fix that gets the CUDA API working again, but the whole process showed the potential for a serious bug (issue #175 ), to be fixed. Please merge ASAP.
=> Hotfix! Bug fix for new PR. 

hdl/axil_to_mcl.v
Fix the returning data to the manycore.
library and spmd simulation test passed.
basejump_stl: b0374c2
bsg_manycore: 75219ce
=> Fix the returning data to endpoint

cl_manycore/libraries/bsg_manycore.cpp, cl_manycore/regression/cuda/test_empty.c
* Adds a check that the destination NPA has valid coordinates.
=> Master issue 258

cl_manycore/libraries/bsg_manycore.cpp, cl_manycore/testbenches/Makefile.vcs
=> Master issue 240

cl_manycore/libraries/bsg_manycore.cpp, cl_manycore/libraries/bsg_manycore_config.cpp, cl_manycore/libraries/bsg_manycore_config.h, cl_manycore/libraries/bsg_manycore_cuda.cpp, cl_manycore/libraries/bsg_manycore_eva.cpp, cl_manycore/regression/cuda/test_empty.c, cl_manycore/regression/library/test_manycore_credits.c, cl_manycore/regression/library/test_manycore_dram_read_write.c, cl_manycore/regression/library/test_manycore_eva.c, cl_manycore/regression/library/test_manycore_vcache_sequence.c, cl_manycore/regression/library/test_rom.c, cl_manycore/regression/library/test_vcache_flush.c, cl_manycore/regression/library/test_vcache_sequence.c, cl_manycore/regression/library/test_vcache_simplified.c, cl_manycore/regression/library/test_vcache_stride.c, cl_manycore/regression/spmd/test_bsg_loader_suite.c, cl_manycore/testbenches/Makefile.vcs
Fixes a bug in hb_mc_manycore_dst_npa_is_valid()
=> Hotfix! Fixes bug in hb_mc_manycore_dst_npa_is_valid

cl_manycore/regression/cuda/Makefile.tests, cl_manycore/regression/cuda/test_multiple_binary_load.c, cl_manycore/regression/cuda/test_multiple_binary_load.h
This regression test is related to issue #300 but doesn't fix it yet.
On both F1 and cosim, the first kernel runs fine but the second kernel hangs.
**Should be merged in with bsg_manycore PR # 67.**
=> Added a new cuda regression test to initialize, load binary run and finish twice

cl_manycore/libraries/bsg_manycore_eva.cpp
This PR addresses bugs in EVA translation and read/write/memset procedures that were expose by running in no-DRAM mode.
=> Fixup EVA translation

cl_manycore/libraries/bsg_manycore.cpp, cl_manycore/libraries/bsg_manycore.h, cl_manycore/regression/library/Makefile.tests, cl_manycore/regression/library/test_read_mem_scatter_gather.c, cl_manycore/regression/library/test_read_mem_scatter_gather.h
This PR refactors buffered memory reads from the manycore to handle response reordering.
=> Load Reordering

cl_manycore/regression/cuda/test_shared_mem_load_store.c
=> Bug fix in cuda test_shared_mem_load_store regression test

cl_manycore/regression/cuda/Makefile.tests
=> Temporarily commented out test_matrix_mul_shared_mem from cuda regression tests

cl_manycore/build/synth.tcl
https://forums.aws.amazon.com/message.jspa?messageID=875737
=> Added set_param hd.clockRoutingWireReduction false to build flow

cl_manycore/testbenches/Makefile.vcs
=> Removed -I flag from VCS flags (no longer supported)

cl_manycore/regression/cuda/Makefile.tests, cl_manycore/regression/cuda/test_float_vec_add.c, cl_manycore/regression/cuda/test_float_vec_add.h
Passes F1.
**Should be merged together with PR # 90 in bsg_manycore.**
=> Added floating point vector addition test for cuda regression

cl_manycore/testbenches/Makefile.common
=> Fixed/Implemented TURBO Mode

cl_manycore/regression/cuda/Makefile.tests, cl_manycore/regression/cuda/test_max_pool2d.c, cl_manycore/regression/cuda/test_max_pool2d.h
**Merge with PR # 108 in bsg_manycore.**
=> Added a cuda max_pool2d regression test

cl_manycore/hardware/bsg_manycore_wrapper.v, cl_manycore/hardware/cl_manycore.sv
=> Updated bsg_manycore_wrapper for with vcache_sets_p parameter

cl_manycore/regression/Makefile, cl_manycore/testbenches/Makefile
* Modified clean and PHONY targets in regression and testbenches makfiles
=> Makefile Improvements

cl_manycore/Makefile.machine.include
=> Switch default memory mode to e_cfg_mem_infinite

cl_manycore/Makefile.machine.include
Reverted to "default" memory system
=> Removed new declarations from Makefile.machine.include

cl_manycore/hardware/cl_manycore.sv, cl_manycore/testbenches/Makefile.common
In preparation for creating a branch with HBM for simulation
=> Removed DMA crossbar from cl_manycore

cl_manycore/Makefile.environment, scripts/afiupload/RepoAction.py, scripts/afiupload/upload.py, scripts/amibuild/bootstrap.init
* Changed Makefile.deps to Makefile.common
* Updated boostrap.init script
* Renamed argument Python script
=> Simplified the build/use process for Bladerunner/F1

cl_manycore/regression/cuda/test_matrix_mul_shared_mem.c
=> Reduced the size of matrix multiplication with shared memory regression test

regression/cl_manycore_regression.h, regression/cuda/test_float_all_ops.c, regression/cuda/test_float_all_ops.h, regression/cuda/test_float_matrix_mul.c, regression/cuda/test_float_matrix_mul.h, regression/cuda/test_float_matrix_mul_shared_mem.c, regression/cuda/test_float_matrix_mul_shared_mem.h, regression/cuda/test_float_vec_add.c, regression/cuda/test_float_vec_add_shared_mem.c, regression/cuda/test_float_vec_div.c, regression/cuda/test_float_vec_div.h, regression/cuda/test_float_vec_exp.c, regression/cuda/test_float_vec_exp.h, regression/cuda/test_float_vec_log.c, regression/cuda/test_float_vec_log.h, regression/cuda/test_float_vec_mul.c, regression/cuda/test_float_vec_mul.h, regression/cuda/test_float_vec_sqrt.c, regression/cuda/test_float_vec_sqrt.h, regression/cuda/tests.mk
- float_vec_add() --> A[i] + B[i] --> C[i]
- float_vec_mul() --> A[i] * B[i] --> C[i]
- float_vec_div() --> A[i] / B[i] --> C[i]
- float_vec_exp() --> exp(A[i]) --> C[i]
- float_matrix_mul 
- float_matrix_mul_shared_mem
- float_all_ops() --> Includes all combinations of corner cases (inf, -inf, nan, -nan, 1/0, 0+inf, inf * 0, etc.) and performs all operations (add, sub, mul, div, compare, float to in convert) on a vector.
At the moment all tests pass except test_float_vec_exp(). @vb000 perhaps you can take a look at this test case and it's corresponding RISCV code in bsg_manycore in PR # 154 . 
**merge with PR # 154 in bsg_manycore.**
=> Added 7 floating point regression tests 

regression/cl_manycore_regression.h
=> Added standard library to cl_manycore_regression.h

hardware/cl_manycore.sv
Added the new signal in the filelist to match the stall trace log branch in bsg_manycore.
Related to PR # 175 in bsg_manycore.
=> Modified the filelist for Tommy's stall_trace_log

testbenches/cosim_wrapper.sv, testbenches/simlibs.mk
=> Display configuration at cosimulation launch

hardware/cl_manycore.sv, libraries/bsg_manycore_cuda.cpp, testbenches/Makefile, testbenches/cosimulation.mk, testbenches/simlibs.mk
File list changes to support vanilla stats parser, and the bloodgraph.
Related to PR #198 and #206 in bsg_manycore.
=> Support for new vanilla bloodgraph and stats parser

libraries/bsg_manycore.cpp, libraries/bsg_manycore_request_packet.h, regression/cl_manycore_regression.h, regression/library/test_vcache_flush.cpp
=> Made test_vcache_flush test lowest and highest word

regression/cuda/test_conv2d.c, regression/cuda/test_conv2d.h, regression/cuda/tests.mk
See https://github.com/bespoke-silicon-group/bsg_manycore/pull/210 for kernel
=> Add 2d convolution test

regression/cuda/test_conv2d.c
=> Fix float generation and comparison

hardware/hardware.mk, testbenches/link.mk, testbenches/simlibs.mk
* Used BSG_MACHINE_PATH instead of CL_DIR to unify with Manycore flow
* Replaced $(CL_DIR)/hardware with $(HARDWARE_PATH)
* Moved definition of WRAPPER_NAME
=> Cleaned up some make variables

hardware/hardware.mk
Corresponds to PR #248 in BSG Manycore
=> Update hardware.mk for changes in arch_filelist.mk (BSG Manycore)

hardware/cl_manycore.sv
* Mirrored changed parameter name in cl_manycore.sv
=> Fix Python Origin issues

README.md, machine.mk, machines/README.md
* Also switched default machine to fast_n_fake
=> Added documentation for the available machines

hardware/cl_manycore.sv
To match  PR # 275 on bsg_manycore.
=> Added trace_en signal to blocking vcache profiler

hardware/cl_manycore.sv
Reverts bespoke-silicon-group/bsg_replicant#543
Merge after #280 in Manycore
=> dRevert "Added trace_en signal to blocking vcache profiler"

regression/cuda/tests.mk
And deprecates the previous barrier test.
Related to PR #287  in bsg_manycore.
=> Adds a template barrier cuda-lite test

regression/pytorch/Makefile, regression/pytorch/test_loader.c, regression/pytorch/test_pytorch.py, regression/pytorch/tests.mk, testbenches/pytorch/Makefile
- Added support for arbitrary python command line arguments in test_loader.
=> Python cmd args

libraries/bsg_manycore_cuda.cpp
This piece of code accidentally got removed by PR #560 . Getting it back in.
=> Getting back accidentally removed code from PR 560

testbenches/simlibs.mk
These files were removed in manycore, so I'm doing the corresponding change here
=> Removed unused files

libraries/bsg_manycore_cuda.h
For application writers who are feeling lazy when writing host code.
=> adds conveniance macro for calling cuda functions

hardware/hardware.mk, libraries/libraries.mk, regression/library/test_rom.c, regression/library/test_rom.h, testbenches/cosimulation.mk, testbenches/simlibs.mk
* Fixes broken test `test_rom`
=> Adds a machine header which is used by test_rom.c

libraries/platforms/aws-fpga/hardware/cl_manycore.sv, libraries/platforms/aws-vcs/hardware.mk
Related to PR # 316 in bsg_manycore.
=> Removing nb_waw_detector from the bsg_replicant

libraries/platforms/aws-fpga/hardware/bsg_manycore_endpoint_to_fifos.v, libraries/platforms/aws-fpga/hardware/cl_manycore.sv
=> Bump to track manycore

build/Makefile, build/aws_build_dcp_from_cl.sh, build/synth.tcl, libraries/platforms/aws-fpga/hardware.mk
* Include .vi files
* Missing (?) bsg_cycle_counter in file list
=> Minor updates for AFI build 

libraries/platforms/aws-fpga/hardware/bsg_manycore_endpoint_to_fifos.v, libraries/platforms/aws-fpga/hardware/cl_manycore.sv
=> Verilog RTL lint fixes

libraries/platforms/aws-vcs/execution.mk
* Nothing was *wrong*, just some files weren't cleaned/precious
=> Fixed precious and clean rules

libraries/platforms/aws-fpga/hardware/cl_manycore.sv, libraries/platforms/dpi-verilator/hardware/dpi_top.sv
Rolled back ruche network changes in #651
=> Vcache profiler support

libraries/bsg_manycore_packet.h, libraries/bsg_manycore_request_packet.h, libraries/bsg_manycore_response_packet.h
Also added a function to copy relevant fields from a request, to a response.
=> Added new accessor functions to packet headers

libraries/bsg_manycore_request_packet.h, libraries/bsg_manycore_response_packet.h
Useful when debugging errant packets
=> Add X/Y information to packet print methods

libraries/bsg_manycore.h
CUDA_CALL is nice. I like nice things.
=> Add BSG_MANYCORE_CALL method

libraries/bsg_manycore.cpp, libraries/bsg_manycore.h
Suggestion from @mrutt92. Fixes #665
=> Add hb_mc_manycore_wait_finish method

libraries/bsg_manycore_epa.h
=> Adding missing macros

examples/cuda/test_loader.c, examples/cuda/test_loader_pod.c, examples/cuda/test_loader_pod.h, libraries/bsg_manycore_config.h, libraries/bsg_manycore_coordinate.h, libraries/bsg_manycore_cuda.cpp, libraries/bsg_manycore_cuda.h
* Adds the new CUDA-lite API for programming Bigblade pods
=> Bigblade CUDA API

examples/cuda/Makefile, libraries/Makefile, libraries/bsg_manycore_cuda.cpp, libraries/bsg_manycore_cuda_legacy_replicate.cpp, libraries/libraries.mk, libraries/platforms/bigblade-vcs/library.mk, libraries/platforms/bigblade-vcs/link.mk
Support for automatically replicating calls to pod API when legacy API is used.
=> Bigblade CUDA Legacy API Replication

examples/library/test_manycore_dmem_read_write.cpp, examples/library/test_manycore_dmem_read_write.hpp, hardware/hardware.mk, libraries/platforms/bigblade-vcs/hardware/dpi_top.sv, machines/pod_X1Y1_ruche_X16Y8_hbm/Makefile.machine.include, machines/pod_X2Y2_ruche_X16Y8_hbm/Makefile.machine.include, machines/pod_X4Y4_ruche_X16Y8_hbm/Makefile.machine.include
* Also fixed hardcoded DMEM base
=> Added profiler-specific parameters

libraries/platforms/dpi-verilator/hardware/dpi_top.sv
needed for https://github.com/bespoke-silicon-group/basejump_stl/pull/367
=> Connect stat_snoop to DRAMSim3 module

libraries/platforms/bigblade-vcs/hardware/dpi_top.sv
Merge after https://github.com/bespoke-silicon-group/bsg_manycore/pull/489
=> Hetero type fixes for Bigblade

libraries/bsg_manycore_eva.cpp
* dram_x_min/max assumed that an origin was passed.
=> Fixed a bug in EVA to NPA translation code

libraries/bsg_manycore.cpp
Packets should use SW, but this required passing sz to the function that set the op. This seemed to break an abstraction so I merged hb_mc_manycore_format_store_request_packet into its single callsite and set SW/STORE there.
Also, refactored to use HB_MC_SUCCESS instead of 0.
=> Slightly refactor store request packet call-tree

examples/cuda/test_dma_valid_invalid/Makefile, examples/cuda/test_dma_valid_invalid/main.cpp
This PR fails pre-[#501](https://github.com/bespoke-silicon-group/bsg_manycore/pull/501) in BSG Manycore, and passes after it.
=> Added test to check DMA invalidation of valid data

environment.mk, libraries/platforms/dpi-verilator/hardware.mk, libraries/platforms/tapeout-vcs/execution.mk
* Changed path for target executable
* Relocated Verilator warning
=> Renamed target simulation binary

examples/cuda/test_credit_csr_tile/Makefile, examples/cuda/test_credit_csr_tile/kernel.cpp, examples/cuda/test_credit_csr_tile/main.c
Hi Dustin, I would like to merge the CSR test of one tile into the tapeout branch.
=> Uploading csr test of one tile

.gitmodules, examples/cuda/bfs/Makefile, examples/cuda/gups/Makefile
Removes subrepos in favor of checking them out.
=> Subrepo removal

libraries/platforms/bigblade-vcs/hardware.mk
According to @dpetrisko, no functionality changes.
=> Dan's DMA Refactor

examples/cuda/test_saifgen/Makefile, examples/cuda/test_saifgen/kernel.cpp, examples/cuda/test_saifgen/main.cpp
Merge after [#638](https://github.com/bespoke-silicon-group/bsg_manycore/pull/638) in bsg_manycore
=> Add saifgen test

examples/apps/fft/common/fft.hpp
* Fixes incorrect loop boundaries and increments in the unrolled FFT twiddle scaling step
=> Minor bug fix in FFT unrolled twiddle factor load

examples/apps/blackscholes/opt-pod/Makefile, examples/apps/blackscholes/opt-single/Makefile, examples/apps/blackscholes/opt-single/bs.hpp, examples/apps/blackscholes/opt-single/kernel.cpp, examples/apps/blackscholes/opt-single/main.cpp
Optimizations to improve throughput of BS
=> BS Optimizations

.gitignore, libraries/platforms/bigblade-vcs/execution.mk, libraries/platforms/bigblade-verilator/execution.mk, libraries/platforms/bigblade-xcelium/execution.mk
Adds bloodgraph target to replicant platforms
=> Adding bloodgraph targets

machines/pod_X1Y1_mesh_X2Y2_hbm_one_pseudo_channel/Makefile.machine.include
This is a tiny machine that can fit on a Pynq Z2. 2x2 mesh, no bells or whistles
=> Adding 2x2 machine

examples/spmd/barrier_in_interrupt/Makefile
This new SPMD test is missing from the bsg_replicant suite
=> Adding barrier in interrupt test

examples/spmd/loader.c, hardware/bsg_bladerunner_mem_cfg_pkg.sv, hardware/bsg_manycore_endpoint_to_fifos.sv, hardware/hardware.mk, machine.mk
Check if this fixes the build for you
=> Hotfixes for build resulting from V->SV migration typos

libraries/platforms/common/dpi/hardware.mk
Adds some missing source files to VSOURCES that are needed for pc-histogram.log, debug.log, and profile.log targets.
=> More fix 10 1

examples/cuda/riscv.mk
Related to https://github.com/bespoke-silicon-group/bsg_manycore/pull/735
=> move rodata to dmem

examples/cuda/riscv.mk
The current llvm path seems to be wrong.
=> Fix llvm bin path

libraries/bsg_manycore_regression.c, libraries/platforms/bigblade-verilator/bsg_manycore_regression_platform.c
Tested with gcc4.8.5, gcc11 and gcc14
=> Fix gcc14 errors
